cabal-version: 3.0

name: hyprmoni
version: 0.1.0.0
license: MIT

common warnings
    ghc-options: -Wall -Werror

executable hyprmoni
    import:
        warnings

    main-is: Main.hs

    other-modules:
        Application,
        Hyprland,
        Json,
        Monitors,
        Selection,
        Types,
        UI

    build-depends:
        base,
        brick,
        bytestring,
        containers,
        network,
        text,
        vty

    hs-source-dirs: app

    ghc-options: -threaded

    default-language: Haskell2010
